### ISSUE TITLE
Unable to locate package linux-headers-4.9.13-moby

### ISSUE THREAD

**Issue by sergeyklay** [geerlingguy/ansible-role-packer-debian#12]
Hello.

We tried to use Packer's builders like:
```js
{
    "type": "docker",
    "image": "phalconphp/build:ubuntu-xenial",
     "export_path": "image.tar"
}
```

and received Ansible error:

```js
{
    "changed":true,
    "cmd":"apt-get -y install linux-headers-$(uname -r)",
    "delta":"0:00:01.265208",
    "end":"2017-05-01 13:35:11.141569",
    "failed":true,
    "rc":100,
    "start":"2017-05-01 13:35:09.876361",
    "stderr":"E: Unable to locate package linux-headers-4.9.13-moby\nE: Couldn't find any package by glob 'linux-headers-4.9.13-moby'\nE: Couldn't find any package by regex 'linux-headers-4.9.13-moby'",
    "stderr_lines":[
        "E: Unable to locate package linux-headers-4.9.13-moby",
        "E: Couldn't find any package by glob 'linux-headers-4.9.13-moby'",
        "E: Couldn't find any package by regex 'linux-headers-4.9.13-moby'"
    ],
    "stdout":"Reading package lists...\nBuilding dependency tree...\nReading state information...",
    "stdout_lines":[
        "Reading package lists...",
        "Building dependency tree...",
        "Reading state information..."
    ]
}
```

Should we use `geerlingguy.packer-debian` for Docker Builder?

**Comment by sergeyklay** [comment]
@geerlingguy What do you think about modifying `main.yml` like:

```yml
- name: Check .dockerenv stat
  stat: path="/.dockerenv"
  register: docker_check

- include: docker.yml
  when: docker_check.stat.exists

- name: Ensure correct kernel headers and openssh-server are installed
  shell: "apt-get -y install linux-headers-$(uname -r)"
  when: not docker_check.stat.exists
```

and creating `docker.yml`. For example:
```yml
---
- name: Install packages
  apt: "name={{ item }} state=installed"
  with_items:
    - openssh-server

- name: Install Docker Python library
  pip: "name={{ item }} state=present"
  with_items:
    - docker-py

- name: Create application group
  group:
    name: vagrant
    gid: 1000

- name: Create application user
  user:
    name: vagrant
    password: vagrant
    uid: 1000
    groups: sudo,vagrant
    append: yes
    shell: /bin/bash
    home: /home/vagrant

- name: Init home directory
  file:
    path: /home/vagrant
    state: directory
    mode:  0755
    owner: vagrant
    group: vagrant
    recurse: yes

- name: Init bashrc
  lineinfile:
    dest: /home/vagrant/.bashrc
    mode:  0770
    owner: vagrant
    group: vagrant
    create: yes
    regexp: "export TERM=xterm"
    line: "export TERM=xterm"
```
