### ISSUE TITLE
The role in version 1.3.0 is broken due to lack of conversion to bool - VMware Tools are not installed correctly

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/ansible-role-packer-debian#16]
Due that you removed forced conversion to bool value of  the variable 'vmware_install_open_vm_tools' the role doesn't install VMware Tools correctly.

The issue introduced by 
https://github.com/geerlingguy/ansible-role-packer-debian/commit/a8c4ae2951725efbbae969a62f3df95aebe61485#diff-14c1998d42ef53373b1aa79e498c6c8a

Please read
1. https://github.com/hashicorp/packer/issues/950
2. https://github.com/ansible/ansible/issues/5392

**Comment by it-praktyk** [comment]
If you would like to confirm you can use the original version of your project
https://github.com/geerlingguy/packer-ubuntu-1604

and modified next modified where a content of the file requirements.yml will be

```yaml
---

- src: geerlingguy.nfs
- src: https://github.com/it-praktyk/ansible-role-packer-debian/
  version: 66e8ba11531ab512478b68a47155dea0c8ca7446
  name: geerlingguy.packer-debian
```
